name: yesod-recaptcha2
version: 1.0.2.1
synopsis: yesod recaptcha2
description: It support new Google reCAPTCHA(v2, v3) for yesod-form instead yesod-recaptcha beacuse original yesod-recaptcha is dead.
github: ncaq/yesod-recaptcha2
license: MIT
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
category: Web
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - http-conduit
  - string-transform
  - text
  - yesod-core
  - yesod-form

library:
  source-dirs: src
