name:                yesod-recaptcha2
version:             0.2.4
synopsis:            yesod recaptcha2
description:         recaptcha2 for yesod-form
github:              ncaq/yesod-recaptcha2
license:             MIT
author:              ncaq
maintainer:          ncaq@ncaq.net
copyright:           © ncaq
category:            Web
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- aeson
- classy-prelude
- http-conduit
- yesod-auth
- yesod-core
- yesod-form

library:
  source-dirs: src
